[package]
name = "ossim_oxide_aux"
version = "0.1.0"
authors = ["dylancannisi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jp2k = "0.3.1"
image = "0.23.10"
